/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    admins: Admin;
    'blog-authors': BlogAuthor;
    'author-photos': AuthorPhoto;
    'blog-posts': BlogPost;
    'blog-cover-images': BlogCoverImage;
    'contact-form-leads': ContactFormLead;
    'blog-tags': BlogTag;
    locations: Location;
    'open-graph-images': OpenGraphImage;
    partners: Partner;
    'partner-logos': PartnerLogo;
    projects: Project;
    'project-assets': ProjectAsset;
    'project-images': ProjectImage;
    services: Service;
    'service-icons': ServiceIcon;
    team: Team;
    'team-member-photos': TeamMemberPhoto;
    technologies: Technology;
    'technology-logos': TechnologyLogo;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {
    'about-page': AboutPage;
    'blog-page': BlogPage;
    common: Common;
    'contact-form': ContactForm;
    'contacts-page': ContactsPage;
    'cookies-policy-page': CookiesPolicyPage;
    footer: Footer;
    general: General;
    'home-page': HomePage;
    'privacy-policy-page': PrivacyPolicyPage;
    'project-footer': ProjectFooter;
    'project-page': ProjectPage;
    'projects-page': ProjectsPage;
    'schedule-meeting-page': ScheduleMeetingPage;
    'sitemap-page': SitemapPage;
    'support-ukraine-page': SupportUkrainePage;
    'terms-of-use-page': TermsOfUsePage;
    languages: Language;
    navigation: Navigation;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: string;
  name: string;
  title?: string | null;
  role: 'root' | 'admin' | 'service';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-authors".
 */
export interface BlogAuthor {
  id: string;
  slug?: string | null;
  photo: string | AuthorPhoto;
  name: string;
  email: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "author-photos".
 */
export interface AuthorPhoto {
  id: string;
  alt?: string | null;
  prefix?: string | null;
  blurhash?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: string;
  content: {
    title: string;
    description?: string | null;
    tags: (string | BlogTag)[];
    author: string | BlogAuthor;
    cover?: string | BlogCoverImage | null;
    content?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | OpenGraphImage | null;
    keywords?: string | null;
    canonical?: string | null;
  };
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-tags".
 */
export interface BlogTag {
  id: string;
  name: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-cover-images".
 */
export interface BlogCoverImage {
  id: string;
  alt?: string | null;
  prefix?: string | null;
  blurhash?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    '700'?: {
      blurhash?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    '800'?: {
      blurhash?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    '1200'?: {
      blurhash?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    '1600'?: {
      blurhash?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "open-graph-images".
 */
export interface OpenGraphImage {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-form-leads".
 */
export interface ContactFormLead {
  id: string;
  firstName: string;
  lastName?: string | null;
  email: string;
  company?: string | null;
  message: string;
  comeFromPage?: string | null;
  comeFromLanguage: 'en' | 'uk' | 'unknown';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: string;
  slug?: string | null;
  order: number;
  timeZone:
    | 'Pacific/Midway'
    | 'Pacific/Niue'
    | 'Pacific/Pago_Pago'
    | 'America/Adak'
    | 'Pacific/Honolulu'
    | 'Pacific/Rarotonga'
    | 'Pacific/Tahiti'
    | 'Pacific/Marquesas'
    | 'America/Anchorage'
    | 'America/Juneau'
    | 'America/Metlakatla'
    | 'America/Nome'
    | 'America/Sitka'
    | 'America/Yakutat'
    | 'Pacific/Gambier'
    | 'America/Los_Angeles'
    | 'America/Tijuana'
    | 'America/Vancouver'
    | 'Pacific/Pitcairn'
    | 'America/Boise'
    | 'America/Cambridge_Bay'
    | 'America/Chihuahua'
    | 'America/Creston'
    | 'America/Dawson'
    | 'America/Dawson_Creek'
    | 'America/Denver'
    | 'America/Edmonton'
    | 'America/Fort_Nelson'
    | 'America/Hermosillo'
    | 'America/Inuvik'
    | 'America/Mazatlan'
    | 'America/Ojinaga'
    | 'America/Phoenix'
    | 'America/Whitehorse'
    | 'America/Yellowknife'
    | 'America/Bahia_Banderas'
    | 'America/Belize'
    | 'America/Chicago'
    | 'America/Costa_Rica'
    | 'America/El_Salvador'
    | 'America/Guatemala'
    | 'America/Indiana/Knox'
    | 'America/Indiana/Tell_City'
    | 'America/Managua'
    | 'America/Matamoros'
    | 'America/Menominee'
    | 'America/Merida'
    | 'America/Mexico_City'
    | 'America/Monterrey'
    | 'America/North_Dakota/Beulah'
    | 'America/North_Dakota/Center'
    | 'America/North_Dakota/New_Salem'
    | 'America/Rainy_River'
    | 'America/Rankin_Inlet'
    | 'America/Regina'
    | 'America/Resolute'
    | 'America/Swift_Current'
    | 'America/Tegucigalpa'
    | 'America/Winnipeg'
    | 'Pacific/Easter'
    | 'Pacific/Galapagos'
    | 'America/Atikokan'
    | 'America/Bogota'
    | 'America/Cancun'
    | 'America/Cayman'
    | 'America/Detroit'
    | 'America/Eirunepe'
    | 'America/Grand_Turk'
    | 'America/Guayaquil'
    | 'America/Havana'
    | 'America/Indiana/Indianapolis'
    | 'America/Indiana/Marengo'
    | 'America/Indiana/Petersburg'
    | 'America/Indiana/Vevay'
    | 'America/Indiana/Vincennes'
    | 'America/Indiana/Winamac'
    | 'America/Iqaluit'
    | 'America/Jamaica'
    | 'America/Kentucky/Louisville'
    | 'America/Kentucky/Monticello'
    | 'America/Lima'
    | 'America/Nassau'
    | 'America/New_York'
    | 'America/Nipigon'
    | 'America/Panama'
    | 'America/Pangnirtung'
    | 'America/Port-au-Prince'
    | 'America/Rio_Branco'
    | 'America/Thunder_Bay'
    | 'America/Toronto'
    | 'America/Anguilla'
    | 'America/Antigua'
    | 'America/Aruba'
    | 'America/Asuncion'
    | 'America/Barbados'
    | 'America/Blanc-Sablon'
    | 'America/Boa_Vista'
    | 'America/Campo_Grande'
    | 'America/Caracas'
    | 'America/Cuiaba'
    | 'America/Curacao'
    | 'America/Dominica'
    | 'America/Glace_Bay'
    | 'America/Goose_Bay'
    | 'America/Grenada'
    | 'America/Guadeloupe'
    | 'America/Guyana'
    | 'America/Halifax'
    | 'America/Kralendijk'
    | 'America/La_Paz'
    | 'America/Lower_Princes'
    | 'America/Manaus'
    | 'America/Marigot'
    | 'America/Martinique'
    | 'America/Moncton'
    | 'America/Montserrat'
    | 'America/Porto_Velho'
    | 'America/Port_of_Spain'
    | 'America/Puerto_Rico'
    | 'America/Santiago'
    | 'America/Santo_Domingo'
    | 'America/St_Barthelemy'
    | 'America/St_Kitts'
    | 'America/St_Lucia'
    | 'America/St_Thomas'
    | 'America/St_Vincent'
    | 'America/Thule'
    | 'America/Tortola'
    | 'Atlantic/Bermuda'
    | 'America/St_Johns'
    | 'America/Araguaina'
    | 'America/Argentina/Buenos_Aires'
    | 'America/Argentina/Catamarca'
    | 'America/Argentina/Cordoba'
    | 'America/Argentina/Jujuy'
    | 'America/Argentina/La_Rioja'
    | 'America/Argentina/Mendoza'
    | 'America/Argentina/Rio_Gallegos'
    | 'America/Argentina/Salta'
    | 'America/Argentina/San_Juan'
    | 'America/Argentina/San_Luis'
    | 'America/Argentina/Tucuman'
    | 'America/Argentina/Ushuaia'
    | 'America/Bahia'
    | 'America/Belem'
    | 'America/Cayenne'
    | 'America/Fortaleza'
    | 'America/Godthab'
    | 'America/Maceio'
    | 'America/Miquelon'
    | 'America/Montevideo'
    | 'America/Paramaribo'
    | 'America/Punta_Arenas'
    | 'America/Recife'
    | 'America/Santarem'
    | 'America/Sao_Paulo'
    | 'Antarctica/Palmer'
    | 'Antarctica/Rothera'
    | 'Atlantic/Stanley'
    | 'America/Noronha'
    | 'Atlantic/South_Georgia'
    | 'America/Scoresbysund'
    | 'Atlantic/Azores'
    | 'Atlantic/Cape_Verde'
    | 'Africa/Abidjan'
    | 'Africa/Accra'
    | 'Africa/Bamako'
    | 'Africa/Banjul'
    | 'Africa/Bissau'
    | 'Africa/Casablanca'
    | 'Africa/Conakry'
    | 'Africa/Dakar'
    | 'Africa/El_Aaiun'
    | 'Africa/Freetown'
    | 'Africa/Lome'
    | 'Africa/Monrovia'
    | 'Africa/Nouakchott'
    | 'Africa/Ouagadougou'
    | 'Africa/Sao_Tome'
    | 'America/Danmarkshavn'
    | 'Antarctica/Troll'
    | 'Atlantic/Canary'
    | 'Atlantic/Faroe'
    | 'Atlantic/Madeira'
    | 'Atlantic/Reykjavik'
    | 'Atlantic/St_Helena'
    | 'Europe/Dublin'
    | 'Europe/Guernsey'
    | 'Europe/Isle_of_Man'
    | 'Europe/Jersey'
    | 'Europe/Lisbon'
    | 'Europe/London'
    | 'Africa/Algiers'
    | 'Africa/Bangui'
    | 'Africa/Brazzaville'
    | 'Africa/Ceuta'
    | 'Africa/Douala'
    | 'Africa/Kinshasa'
    | 'Africa/Lagos'
    | 'Africa/Libreville'
    | 'Africa/Luanda'
    | 'Africa/Malabo'
    | 'Africa/Ndjamena'
    | 'Africa/Niamey'
    | 'Africa/Porto-Novo'
    | 'Africa/Tunis'
    | 'Africa/Windhoek'
    | 'Arctic/Longyearbyen'
    | 'Europe/Amsterdam'
    | 'Europe/Andorra'
    | 'Europe/Belgrade'
    | 'Europe/Berlin'
    | 'Europe/Bratislava'
    | 'Europe/Brussels'
    | 'Europe/Budapest'
    | 'Europe/Copenhagen'
    | 'Europe/Gibraltar'
    | 'Europe/Ljubljana'
    | 'Europe/Luxembourg'
    | 'Europe/Madrid'
    | 'Europe/Malta'
    | 'Europe/Monaco'
    | 'Europe/Oslo'
    | 'Europe/Paris'
    | 'Europe/Podgorica'
    | 'Europe/Prague'
    | 'Europe/Rome'
    | 'Europe/San_Marino'
    | 'Europe/Sarajevo'
    | 'Europe/Skopje'
    | 'Europe/Stockholm'
    | 'Europe/Tirane'
    | 'Europe/Vaduz'
    | 'Europe/Vatican'
    | 'Europe/Vienna'
    | 'Europe/Warsaw'
    | 'Europe/Zagreb'
    | 'Europe/Zurich'
    | 'Africa/Blantyre'
    | 'Africa/Bujumbura'
    | 'Africa/Cairo'
    | 'Africa/Gaborone'
    | 'Africa/Harare'
    | 'Africa/Johannesburg'
    | 'Africa/Juba'
    | 'Africa/Khartoum'
    | 'Africa/Kigali'
    | 'Africa/Lubumbashi'
    | 'Africa/Lusaka'
    | 'Africa/Maputo'
    | 'Africa/Maseru'
    | 'Africa/Mbabane'
    | 'Africa/Tripoli'
    | 'Asia/Amman'
    | 'Asia/Beirut'
    | 'Asia/Damascus'
    | 'Asia/Famagusta'
    | 'Asia/Gaza'
    | 'Asia/Hebron'
    | 'Asia/Jerusalem'
    | 'Asia/Nicosia'
    | 'Europe/Athens'
    | 'Europe/Bucharest'
    | 'Europe/Chisinau'
    | 'Europe/Helsinki'
    | 'Europe/Kaliningrad'
    | 'Europe/Kyiv'
    | 'Europe/Mariehamn'
    | 'Europe/Riga'
    | 'Europe/Sofia'
    | 'Europe/Tallinn'
    | 'Europe/Uzhgorod'
    | 'Europe/Vilnius'
    | 'Europe/Zaporozhye'
    | 'Africa/Addis_Ababa'
    | 'Africa/Asmara'
    | 'Africa/Dar_es_Salaam'
    | 'Africa/Djibouti'
    | 'Africa/Kampala'
    | 'Africa/Mogadishu'
    | 'Africa/Nairobi'
    | 'Antarctica/Syowa'
    | 'Asia/Aden'
    | 'Asia/Baghdad'
    | 'Asia/Bahrain'
    | 'Asia/Kuwait'
    | 'Asia/Qatar'
    | 'Asia/Riyadh'
    | 'Europe/Istanbul'
    | 'Europe/Kirov'
    | 'Europe/Minsk'
    | 'Europe/Moscow'
    | 'Europe/Volgograd'
    | 'Indian/Antananarivo'
    | 'Indian/Comoro'
    | 'Indian/Mayotte'
    | 'Asia/Tehran'
    | 'Asia/Baku'
    | 'Asia/Dubai'
    | 'Asia/Muscat'
    | 'Asia/Tbilisi'
    | 'Asia/Yerevan'
    | 'Europe/Astrakhan'
    | 'Europe/Samara'
    | 'Europe/Saratov'
    | 'Europe/Ulyanovsk'
    | 'Indian/Mahe'
    | 'Indian/Mauritius'
    | 'Indian/Reunion'
    | 'Asia/Kabul'
    | 'Antarctica/Mawson'
    | 'Asia/Aqtau'
    | 'Asia/Aqtobe'
    | 'Asia/Ashgabat'
    | 'Asia/Atyrau'
    | 'Asia/Dushanbe'
    | 'Asia/Karachi'
    | 'Asia/Oral'
    | 'Asia/Qyzylorda'
    | 'Asia/Samarkand'
    | 'Asia/Tashkent'
    | 'Asia/Yekaterinburg'
    | 'Indian/Kerguelen'
    | 'Indian/Maldives'
    | 'Asia/Colombo'
    | 'Asia/Kolkata'
    | 'Asia/Kathmandu'
    | 'Antarctica/Vostok'
    | 'Asia/Almaty'
    | 'Asia/Bishkek'
    | 'Asia/Dhaka'
    | 'Asia/Omsk'
    | 'Asia/Qostanay'
    | 'Asia/Thimphu'
    | 'Asia/Urumqi'
    | 'Indian/Chagos'
    | 'Asia/Yangon'
    | 'Indian/Cocos'
    | 'Antarctica/Davis'
    | 'Asia/Bangkok'
    | 'Asia/Barnaul'
    | 'Asia/Hovd'
    | 'Asia/Ho_Chi_Minh'
    | 'Asia/Jakarta'
    | 'Asia/Krasnoyarsk'
    | 'Asia/Novokuznetsk'
    | 'Asia/Novosibirsk'
    | 'Asia/Phnom_Penh'
    | 'Asia/Pontianak'
    | 'Asia/Tomsk'
    | 'Asia/Vientiane'
    | 'Indian/Christmas'
    | 'Asia/Brunei'
    | 'Asia/Choibalsan'
    | 'Asia/Hong_Kong'
    | 'Asia/Irkutsk'
    | 'Asia/Kuala_Lumpur'
    | 'Asia/Kuching'
    | 'Asia/Macau'
    | 'Asia/Makassar'
    | 'Asia/Manila'
    | 'Asia/Shanghai'
    | 'Asia/Singapore'
    | 'Asia/Taipei'
    | 'Asia/Ulaanbaatar'
    | 'Australia/Perth'
    | 'Australia/Eucla'
    | 'Asia/Chita'
    | 'Asia/Dili'
    | 'Asia/Jayapura'
    | 'Asia/Khandyga'
    | 'Asia/Pyongyang'
    | 'Asia/Seoul'
    | 'Asia/Tokyo'
    | 'Asia/Yakutsk'
    | 'Pacific/Palau'
    | 'Australia/Adelaide'
    | 'Australia/Broken_Hill'
    | 'Australia/Darwin'
    | 'Antarctica/DumontDUrville'
    | 'Antarctica/Macquarie'
    | 'Asia/Ust-Nera'
    | 'Asia/Vladivostok'
    | 'Australia/Brisbane'
    | 'Australia/Currie'
    | 'Australia/Hobart'
    | 'Australia/Lindeman'
    | 'Australia/Melbourne'
    | 'Australia/Sydney'
    | 'Pacific/Chuuk'
    | 'Pacific/Guam'
    | 'Pacific/Port_Moresby'
    | 'Pacific/Saipan'
    | 'Australia/Lord_Howe'
    | 'Antarctica/Casey'
    | 'Asia/Magadan'
    | 'Asia/Sakhalin'
    | 'Asia/Srednekolymsk'
    | 'Pacific/Bougainville'
    | 'Pacific/Efate'
    | 'Pacific/Guadalcanal'
    | 'Pacific/Kosrae'
    | 'Pacific/Norfolk'
    | 'Pacific/Noumea'
    | 'Pacific/Pohnpei'
    | 'Antarctica/McMurdo'
    | 'Asia/Anadyr'
    | 'Asia/Kamchatka'
    | 'Pacific/Auckland'
    | 'Pacific/Fiji'
    | 'Pacific/Funafuti'
    | 'Pacific/Kwajalein'
    | 'Pacific/Majuro'
    | 'Pacific/Nauru'
    | 'Pacific/Tarawa'
    | 'Pacific/Wake'
    | 'Pacific/Wallis'
    | 'Pacific/Chatham'
    | 'Pacific/Apia'
    | 'Pacific/Enderbury'
    | 'Pacific/Fakaofo'
    | 'Pacific/Tongatapu'
    | 'Pacific/Kiritimati';
  name: string;
  address: string;
  url: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  coordinates: [number, number];
  fullName: string;
  title: string;
  phone?: string | null;
  email?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: string;
  slug?: string | null;
  order: number;
  viewType: 'default' | 'big';
  logo: string | PartnerLogo;
  name: string;
  url: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-logos".
 */
export interface PartnerLogo {
  id: string;
  alt?: string | null;
  prefix?: string | null;
  blurhash?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  preview: {
    name: string;
    description: string;
    image: string | ProjectImage;
  };
  content: {
    name: string;
    description: string;
    image: string | ProjectAsset;
    details: {
      country:
        | 'af'
        | 'al'
        | 'dz'
        | 'ad'
        | 'ao'
        | 'ag'
        | 'ar'
        | 'am'
        | 'au'
        | 'at'
        | 'az'
        | 'bs'
        | 'bh'
        | 'bd'
        | 'bb'
        | 'by'
        | 'be'
        | 'bz'
        | 'bj'
        | 'bt'
        | 'bo'
        | 'ba'
        | 'bw'
        | 'br'
        | 'bn'
        | 'bg'
        | 'bf'
        | 'bi'
        | 'cv'
        | 'kh'
        | 'cm'
        | 'ca'
        | 'cf'
        | 'td'
        | 'cl'
        | 'cn'
        | 'co'
        | 'km'
        | 'cg'
        | 'cd'
        | 'cr'
        | 'ci'
        | 'hr'
        | 'cu'
        | 'cy'
        | 'cz'
        | 'dk'
        | 'dj'
        | 'dm'
        | 'do'
        | 'ec'
        | 'eg'
        | 'sv'
        | 'gq'
        | 'er'
        | 'ee'
        | 'sz'
        | 'et'
        | 'fj'
        | 'fi'
        | 'fr'
        | 'ga'
        | 'gm'
        | 'ge'
        | 'de'
        | 'gh'
        | 'gr'
        | 'gd'
        | 'gt'
        | 'gn'
        | 'gw'
        | 'gy'
        | 'ht'
        | 'hn'
        | 'hu'
        | 'is'
        | 'in'
        | 'id'
        | 'ir'
        | 'iq'
        | 'ie'
        | 'il'
        | 'it'
        | 'jm'
        | 'jp'
        | 'jo'
        | 'kz'
        | 'ke'
        | 'ki'
        | 'kp'
        | 'kr'
        | 'kw'
        | 'kg'
        | 'la'
        | 'lv'
        | 'lb'
        | 'ls'
        | 'lr'
        | 'ly'
        | 'li'
        | 'lt'
        | 'lu'
        | 'mg'
        | 'mw'
        | 'my'
        | 'mv'
        | 'ml'
        | 'mt'
        | 'mh'
        | 'mr'
        | 'mu'
        | 'mx'
        | 'fm'
        | 'md'
        | 'mc'
        | 'mn'
        | 'me'
        | 'ma'
        | 'mz'
        | 'mm'
        | 'na'
        | 'nr'
        | 'np'
        | 'nl'
        | 'nz'
        | 'ni'
        | 'ne'
        | 'ng'
        | 'mk'
        | 'no'
        | 'om'
        | 'pk'
        | 'pw'
        | 'pa'
        | 'pg'
        | 'py'
        | 'pe'
        | 'ph'
        | 'pl'
        | 'pt'
        | 'qa'
        | 'ro'
        | 'ru'
        | 'rw'
        | 'kn'
        | 'lc'
        | 'vc'
        | 'ws'
        | 'sm'
        | 'st'
        | 'sa'
        | 'sn'
        | 'rs'
        | 'sc'
        | 'sl'
        | 'sg'
        | 'sk'
        | 'si'
        | 'sb'
        | 'so'
        | 'za'
        | 'ss'
        | 'es'
        | 'lk'
        | 'sd'
        | 'sr'
        | 'se'
        | 'ch'
        | 'sy'
        | 'tj'
        | 'tz'
        | 'th'
        | 'tl'
        | 'tg'
        | 'to'
        | 'tt'
        | 'tn'
        | 'tr'
        | 'tm'
        | 'tv'
        | 'ug'
        | 'ua'
        | 'ae'
        | 'gb'
        | 'us'
        | 'uy'
        | 'uz'
        | 'vu'
        | 've'
        | 'vn'
        | 'ye'
        | 'zm'
        | 'zw';
      url: string;
      startYear: number;
      endYear?: number | null;
      industry: string;
      projectType: string;
      services: string;
      technologies: string;
    };
    layout: (
      | {
          options?: {
            autoplay?: boolean | null;
            loop?: boolean | null;
            animation?: ('slide' | 'fade') | null;
          };
          slides?:
            | {
                image?: string | ProjectAsset | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'slider';
        }
      | {
          content: {
            root: {
              type: string;
              children: {
                type: string;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
          blockName?: string | null;
          blockType: 'rich-text';
        }
      | {
          color: string;
          default: {
            show: boolean;
            x?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            y?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            blur?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            diameter?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
          };
          phone: {
            show: boolean;
            x?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            y?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            blur?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            diameter?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
          };
          'large-phone': {
            show: boolean;
            x?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            y?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            blur?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            diameter?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
          };
          tablet: {
            show: boolean;
            x?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            y?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            blur?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            diameter?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
          };
          'large-tablet': {
            show: boolean;
            x?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            y?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            blur?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            diameter?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
          };
          laptop: {
            show: boolean;
            x?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            y?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            blur?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            diameter?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
          };
          'large-laptop': {
            show: boolean;
            x?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            y?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            blur?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            diameter?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
          };
          desktop: {
            show: boolean;
            x?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            y?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            blur?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
            diameter?: {
              value?: number | null;
              unit?: ('px' | 'rem' | '%' | 'vw') | null;
            };
          };
          id?: string | null;
          blockName?: string | null;
          blockType: 'circle-element';
        }
      | {
          columns?:
            | {
                blocks?:
                  | (
                      | {
                          content: {
                            root: {
                              type: string;
                              children: {
                                type: string;
                                version: number;
                                [k: string]: unknown;
                              }[];
                              direction: ('ltr' | 'rtl') | null;
                              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                              indent: number;
                              version: number;
                            };
                            [k: string]: unknown;
                          };
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'rich-text';
                        }
                      | {
                          media: string | ProjectAsset;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'media';
                        }
                    )[]
                  | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'columns';
        }
    )[];
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | OpenGraphImage | null;
    keywords?: string | null;
    canonical?: string | null;
  };
  slug?: string | null;
  order: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-images".
 */
export interface ProjectImage {
  id: string;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    '700'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    '800'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    '1200'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    '1600'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-assets".
 */
export interface ProjectAsset {
  id: string;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    '700'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    '800'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    '1200'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    '1600'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  slug?: string | null;
  order: number;
  icon: string | ServiceIcon;
  name: string;
  description: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-icons".
 */
export interface ServiceIcon {
  id: string;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: string;
  slug?: string | null;
  order: number;
  photo: string | TeamMemberPhoto;
  firstName: string;
  lastName?: string | null;
  title: string;
  fullTitle: string;
  about?: string | null;
  links?:
    | {
        name: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-member-photos".
 */
export interface TeamMemberPhoto {
  id: string;
  alt?: string | null;
  prefix?: string | null;
  blurhash?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    '700'?: {
      blurhash?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    '800'?: {
      blurhash?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    '1200'?: {
      blurhash?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    '1600'?: {
      blurhash?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies".
 */
export interface Technology {
  id: string;
  slug?: string | null;
  order: number;
  name: string;
  logo: string | TechnologyLogo;
  description: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technology-logos".
 */
export interface TechnologyLogo {
  id: string;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'admins';
    value: string | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: string;
  content: {
    translation?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | OpenGraphImage | null;
    keywords?: string | null;
    canonical?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: string;
  content: {
    translation?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | OpenGraphImage | null;
    keywords?: string | null;
    canonical?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "common".
 */
export interface Common {
  id: string;
  translation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-form".
 */
export interface ContactForm {
  id: string;
  translation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts-page".
 */
export interface ContactsPage {
  id: string;
  content: {
    translation?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | OpenGraphImage | null;
    keywords?: string | null;
    canonical?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookies-policy-page".
 */
export interface CookiesPolicyPage {
  id: string;
  content: {
    translation?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | OpenGraphImage | null;
    keywords?: string | null;
    canonical?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  translation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general".
 */
export interface General {
  id: string;
  phone: string;
  email: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  content: {
    translation?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | OpenGraphImage | null;
    keywords?: string | null;
    canonical?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy-page".
 */
export interface PrivacyPolicyPage {
  id: string;
  content: {
    translation?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | OpenGraphImage | null;
    keywords?: string | null;
    canonical?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-footer".
 */
export interface ProjectFooter {
  id: string;
  title: string;
  description: string;
  contactFormButton: string;
  link: {
    label: string;
    url: string;
  };
  contact?: (string | null) | Team;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-page".
 */
export interface ProjectPage {
  id: string;
  translation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page".
 */
export interface ProjectsPage {
  id: string;
  content: {
    translation?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | OpenGraphImage | null;
    keywords?: string | null;
    canonical?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-meeting-page".
 */
export interface ScheduleMeetingPage {
  id: string;
  content: {
    translation?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | OpenGraphImage | null;
    keywords?: string | null;
    canonical?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sitemap-page".
 */
export interface SitemapPage {
  id: string;
  content: {
    translation?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | OpenGraphImage | null;
    keywords?: string | null;
    canonical?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-ukraine-page".
 */
export interface SupportUkrainePage {
  id: string;
  content: {
    translation?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | OpenGraphImage | null;
    keywords?: string | null;
    canonical?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-of-use-page".
 */
export interface TermsOfUsePage {
  id: string;
  content: {
    translation?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | OpenGraphImage | null;
    keywords?: string | null;
    canonical?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "languages".
 */
export interface Language {
  id: string;
  translation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  translation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}